name: tom.roffe.uk
services:
  tom-roffe-uk:
    build:
      context: ../../
      dockerfile: docker/production/Dockerfile
    image: ghcr.io/tomroffe/tom-roffe-uk:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

